language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"

script: py.test

notifications:
        email:
        - kapilgarg1996@gmail.com
        - kapilphalswal3@gmail.com
        - coffeewithkaran007@gmail.com
